spring:
  application:
    name: chatting
  datasource:
    url: jdbc:mysql://localhost:3307/chat_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: chatuser
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6380

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9093


server:
  servlet:
    session:
      timeout: 30m  # 30분 세션 유지

